[tool]
[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "numpy>=1.24.2",
]
requires-python = ">=3.8"
license = {text = "MIT"}
